spring:
    cors:
      allowed-origins:
        - http://localhost:5173  # 프론트엔드 도메인 주소
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS  # OPTIONS 메서드를 허용하는 것이 좋습니다.
    allowed-headers:
      - "*"  # 모든 헤더를 허용합니다. 필요에 따라 필터링 가능
    allow-credentials: true  # 자격증명 (쿠키, 헤더)을 허용할지 여부
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mainProject?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dnwls4545!
  jpa:          #JPA 설정
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
logging:         #로그 레벨 설정
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: asdlkfjaasfljqlkj3rlkj123l41j234l1234l1j234
  access-token-expiration-minutes: 120
  refresh-token-expiration-minutes: 420
  #